# Generated by Django 5.1.7 on 2025-03-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindiseaseprediction',
            name='chatbot_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
