# Generated by Django 5.1.7 on 2025-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiseasehistory',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdiseasehistory',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='userdiseasehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skindiseaseprediction',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skindiseaseprediction',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='UserDiseaseHistory',
        ),
    ]
