# Generated by Django 5.1.7 on 2025-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_skindiseaseprediction_chatbot_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skindiseaseprediction',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
