# Generated by Django 5.1.7 on 2025-03-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_skindiseaseprediction_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermatologist',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='country',
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dermatologist',
            name='phone_number',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='dermatologist',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
