# Generated by Django 5.1.7 on 2025-03-28 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_remove_dermatologist_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_disease', models.CharField(max_length=100, null=True)),
                ('confidence_score', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.conversationsession'),
        ),
        migrations.AddField(
            model_name='skindiseaseprediction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.conversationsession'),
        ),
    ]
