# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - aid-dermatilogy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
          AZURE_AI_SEARCH_KEY: ${{ secrets.AZURE_AI_SEARCH_KEY}}
          AZURE_AI_SEARCH_ENDPOINT: ${{ secrets.AZURE_AI_SEARCH_ENDPOINT}}
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          cd endpoints
          pip install -r requirements.txt

      - name: Run migrations in build (validation)
        run: |
          source venv/bin/activate
          cd endpoints
          python manage.py migrate --noinput

      - name: Collect static files
        run: |
          source venv/bin/activate
          cd endpoints
          python manage.py collectstatic --noinput

      - name: Prepare deployment files
        run: |
          # Create startup script at root
          echo '#!/bin/bash' > startup.sh
          echo 'cd /home/site/wwwroot' >> startup.sh
          echo 'pip install -r requirements.txt' >> startup.sh
          echo 'python manage.py migrate --noinput' >> startup.sh
          echo 'gunicorn --bind=0.0.0.0 --timeout 600 endpoints.wsgi' >> startup.sh
          chmod +x startup.sh

          # Move all files to deployment directory
          mkdir -p deployment
          cp -r endpoints/* deployment/
          cp startup.sh deployment/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "aid-dermatilogy"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68C025B29C09438CB9C20318E1CD582B }}
